### ISSUE TITLE
Node part does not work on MAC

### ISSUE THREAD

**Issue by harschell** [imodeljs/imodel-unity-example#1]
Node part does not work on MAC though it perfectly worked on windows 
On mac when I try to npm build it says Faild at the imodel-unity--example@ build script and many other error

**Comment by ColinKerr** [comment]
We do not support MacOS at this time, we only support windows and linux.  Mac support is being worked on but I do not have a timeline to share at the moment.  

Please see our supported Platform page for details on OS support: https://github.com/imodeljs/imodeljs/blob/master/docs/learning/SupportedPlatforms.md

**Comment by harschell** [comment]
Thanks. Somehow I forgot to check if imodeljs supports MAC OS/OSX.
It would be great if you let us know once it is supported for MacOS.

**Comment by mgooding** [comment]
@harschell - the latest update should work with MacOS.

**Comment by harschell** [comment]
thank you for update I'll check it out.
