### ISSUE TITLE
Logger Issue

### ISSUE THREAD

**Issue by suman752** [imodeljs/imodel-unity-example#2]
Enable/Disable logger in whole Unity project, any document plz share

**Comment by mgooding** [comment]
Can you clarify what you're looking to do? Do you want to disable Debug.Log messages in Unity, the logging messages on the Node backend, or both?

**Comment by suman752** [comment]
Want to off both

**Comment by mgooding** [comment]
1) For Unity, you can turn off all logging with https://docs.unity3d.com/ScriptReference/ILogger-logEnabled.html.
2) For the Node backend, you can alter what's logged here: https://github.com/imodeljs/imodel-unity-example/blob/master/node/src/Main.ts#L188
